import React from 'react'
import Head from 'next/head'
import axios from 'axios'
import Slider from "react-slick";
import Price from 'react-price';

import Header from '../components/header/Header'
import Newsletter from '../components/newsletter/Newsletter'
import ProductContainer from '../components/productContainer/ProductContainer'
import Footer from '../components/footer/Footer'

import { CarrProdutos } from './styles';
import Banner from '../components/banner/Banner';

const Home = ({ products, error }) => {
    const settings = {
        dots: true,
        infinite: false,
        speed: 500,
        dots: false,
        slidesToShow: 4,
        slidesToScroll: 4,
        initialSlide: 0,
        responsive: [
            {
                breakpoint: 1024,
                settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3,
                    infinite: true,
                    dots: true
                }
            },
            {
                breakpoint: 600,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2,
                    initialSlide: 2,
                    dots: true,
                    arrows: false
                }
            },
            {
                breakpoint: 480,
                settings: {
                    slidesToShow: 2,
                    dots: true,
                    arrows: false,
                    slidesToScroll: 1
                }
            }
        ]
    };

    return (
        <>
            <Head>
                <title>Corebiz</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800;900&display=swap" rel="stylesheet" />

                <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
                <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />

            </Head>

            <Header />

            <Banner />

            <CarrProdutos>
                <h3>Mais Vendidos</h3>

                <Slider {...settings}>
                    {products.map(product => (
                        <div key={product.productId}>
                           
                            <ProductContainer
                                productName={product.productName}
                                stars={product.stars}
                                imageUrl={product.imageUrl}
                                listPrice={product.listPrice}
                                price={product.price}
                                quantity={product.installments.quantity}
                                value={product.installments.value}
                            />

                           
                        </div>
                    ))}
                </Slider>
            </CarrProdutos>




            <Newsletter />
            <Footer />




        </>
    )
}


Home.getInitialProps = async ctx => {
    try {
        const res = await axios.get('https://corebiz-test.herokuapp.com/api/v1/products');
        const products = res.data;
        return { products };
    } catch (error) {
        return { error };
    }
};



export default Home
